## USB port
port: "/dev/serial/by-id/usb-SparkFun_SparkFun_SAMD21_FCF914F8504D3148372E3120FF121018-if00"

## Frame used as a TF in ROS
frame_id: "imu_link"

print_calibration: true

##### Calibration ####
### accelerometer
accel_x_min: -250.0
accel_x_max: 250.0
accel_y_min: -250.0
accel_y_max: 250.0
accel_z_min: -250.0
accel_z_max: 250.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration

calibration_magn_use_extended: true
magn_ellipsoid_center: [200.100, 287.827, 80.2047]
magn_ellipsoid_transform: [[0.982445, -0.0211691, -0.00269070], [-0.0211691, 0.965760, -0.0118721], [-0.00269070, -0.0118721, 0.991044]]


# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 0.0
gyro_average_offset_y: 0.0
gyro_average_offset_z: 0.0
